version: '3'

services:
  app:
    build:
      context: ./php-app
      dockerfile: Dockerfile.php
    ports:
      - "8082:80"
    volumes:
      - ./php-app:/var/www/html
    expose:
      - "80"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:  
      - ./database:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - "8083:80"
    environment:
      PMA_ARBITRARY: 1